### ISSUE TITLE
Compression should happen after serialization

### ISSUE THREAD

**Issue by wedgwood** [fastify/fastify-compress#10]
As titled, compression is for string-like or buffer-like variable, so should it happen after serialization at the end of `SendEnd`?

**Comment by delvedor** [comment]
I'm not sure I've understood your question.
The compression happens **after** the serialization.

**Comment by wedgwood** [comment]
Hi, @delvedor .
It seems not the order. I found the current order is
`reply.send()` -> `hooks.onSend()` -> `reply._serializer(payload)`. And compression registered in `hooks.onSend`. If object (such as `{hello: 'world'}`) be sent, the object will be compressed first then serialized. How could an object be compressed? Unexpected behavior happens.

**Comment by delvedor** [comment]
No, the order is:
- the user calls `reply.send`
- the hook `onSend` is triggered
- `fastify-compress` hook is executed
  - if the payload is a stream => compress
  - if the payload is a string => compress
  - if the payload is an object => serialize => compress
- fastify sends the compressed data

If you are not convinced try to write a test (o read [ours](https://github.com/fastify/fastify-compress/blob/master/test.js)) :)

**Comment by wedgwood** [comment]
Sorry, my fault, I have not review the code carefully. Now I get it. Thx!
