### ISSUE TITLE
Brotli not getting chosen

### ISSUE THREAD

**Issue by nhumrich** [fastify/fastify-compress#103]
## 💬 Questions and Help

The readme says that compression is chosen in this order:
Brotli (br) -> gzip -> deflate

When I test it, my browser sends the following accept-encoding header:
`gzip, deflate, br`

I am curious as to why brotli isn't being selected? Is there something I am doing wrong? 

My code just registers fastify-compress without anything special, version 2.0.0

**Comment by Eomm** [comment]
Could you add a reproducible code?

**Comment by nhumrich** [comment]
Sure. Here are the steps I use to reproduce (you probably dont need all these things, but its just an example)

1. install dependencies (fastify and fastify-compress)
2. make a file temp.js
``` javascript
const fastify = require('fastify')
const fcompress = require('fastify-compress')


const server = fastify({ logger: true })
server.register(fcompress, {global: true}).
get('/hello', async (req, rep) => {
    console.log(req.headers)
    return {'this': 'is', 'some': 'really large object',
    'it': 'has a lot of text so that it gets compressed',
    'nums': Array.from(Array(1000).keys())}
}).listen(5000, '0.0.0.0', () => {
    console.log('listening...')
})
```
3. Run the file `node temp.js`
4. Run Ngrox `ngrok http 5000`   (Note: this is needed because browsers only use brotli on https)
5. Open up firefox
6. Go to the ngrox https url (not the http (non-s) ones)
7. Open network tab. 
8. Type in `/hello` at the end of the url
9. Notice the request and response headers. Came back as gzip, not brotli. You will note the request headers also in your terminal.

**Comment by Eomm** [comment]
what it is the output of the `console.log(req.headers)`?
Did you try without `ngrok`?

Because it seems a specific problem since a simple curl reply as expected:

```
curl 'http://localhost:5000/hello' -H 'accept-encoding: gzip, deflate, br' -v

# print
> GET /hello HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.65.3
> Accept: */*
> accept-encoding: gzip, deflate, br
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-encoding: br
< Date: Thu, 12 Mar 2020
< Connection: keep-alive
< Transfer-Encoding: chunked
<
```

**Comment by nhumrich** [comment]
``` bash
 curl 'http://localhost:5000/hello' -H 'accept-encoding: gzip, deflate, br' -v           42.4m  Thu 12 Mar 2020 11:43:09 AM MDT
*   Trying ::1:5000...
* connect to ::1 port 5000 failed: Connection refused
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /hello HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.69.0
> Accept: */*
> accept-encoding: gzip, deflate, br
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-encoding: gzip
< Date: Thu, 12 Mar 2020 17:44:49 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 10)
* Failed reading the chunked-encoded stream
* Closing connection 0
```

and output: 
```
{
  host: 'localhost:5000',
  'user-agent': 'curl/7.69.0',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate, br'
}```

**Comment by nhumrich** [comment]
After trying many ways to reproduce, it started working after I updated all dependencies. possibly a bug in an older version of fastify.
