### ISSUE TITLE
Should fastify-compress handle compressed income requests?

### ISSUE THREAD

**Issue by joelwallis** [fastify/fastify-compress#105]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

Fastify currently does not accept requests with `Content-Encoding: gzip` in its normal form, and since there is a generic module for compression-related work in the Fastify ecosystem, I think it would be good to extend its capabilities to support compressed incoming requests.

## Motivation

Compression in HTTP is useful in HTTP requests too, not only in HTTP responses.

## Example

An HTTP client would send a compressed HTTP request to a Fastify server using fastify-compress, and it would be handled properly.

**Comment by mcollina** [comment]
I agree, it would be a good feature! Would you like to send a PR?

**Comment by joelwallis** [comment]
I would love to! However, I don't have much experience with Fastify or its codebase, so I would happily receive guidance/feedback on my PR. :-)

**Comment by mcollina** [comment]
This needs to be investigated, I'm not necessarily sure on how and it might require some effort on Fastify itself.

**Comment by ShogunPanda** [comment]
Shall this be closed?
