### ISSUE TITLE
Allow tuning of Brotli compression level

### ISSUE THREAD

**Issue by iansltx** [fastify/fastify-compress#106]
## 🚀 Feature Proposal

Add ability to specify brotli compression level, preferably globally

## Motivation

Brotli is great for compressing static assets, where you can amortize the cost of compression across multiple responses, however in its default configuration it takes an extremely (multiple orders of magnitude vs. gzip) long time to compress data, making it a hard sell for dynamic content, particularly compared to near-instant compression provided by gzip/deflate. Given that in e.g. NestJS the compression phase happens after responses are pulled from cache on the Nest side, even aggressively server-side cached responses can't amortize exprensive compression operations across multiple requests.

Turning down the compression level on brotli may allow for acceptable compression times while still maintaining a compression ratio superior to gzip/deflate.

## Example

When specifying brotli as a compression method, add a `level` parameter to the object. I'm guessing that the default is maximum compression (11?), and for BC reasons it'd be reasonable to keep that default if the `level` parameter wasn't provided.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by iansltx** [comment]
From a quick look at the codez the solution didn't seem obvious, but if I wind up with time to circle back to this (we're going with gzip/deflate now) I'll try for a PR if one hasn't yet been built.

**Comment by delvedor** [comment]
Closed in https://github.com/fastify/fastify-compress/pull/113.
