### ISSUE TITLE
Add Vary header to response

### ISSUE THREAD

**Issue by adityapatadia** [fastify/fastify-compress#108]
## 🚀 Feature Proposal

Ideally, `vary: accept-encoding` header should be added to responses which are compressed by this module. If any `vary` header is already present in response, `accept-encoding` should be added as comma separated value.

## Motivation

https://tools.ietf.org/html/rfc7234#section-4.1 and https://tools.ietf.org/html/rfc7231#section-7.1.4

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Arnovsky** [comment]
If possible I'd like to take it.

**Comment by mcollina** [comment]
go for it!
