### ISSUE TITLE
Remove unnecessary log

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-compress#114]
https://github.com/fastify/fastify-compress/issues/37

I don't think there needs to be a log at all in the case where isn't any data to compress. The plugin should just be a noop in this case.

As it currently stands, I had no idea where this "compress: missing payload" log was coming from until I did a web search ([https://duckduckgo.com/?q="compress%3A+missing+payload"&t=vivaldi&ia=web&iai=r1-0&page=1&adx=sltb&sexp={"v7exp"%3A"a"%2C"sltexp"%3A"b"}](https://duckduckgo.com/?q="compress%3A+missing+payload"&t=vivaldi&ia=web&iai=r1-0&page=1&adx=sltb&sexp={"v7exp"%3A"a"%2C"sltexp"%3A"b"})) and the _only returned result_ was the original issue about this log message. So at a minimum this log needs to be clearer about where it comes from.

**Comment by mcollina** [comment]
I would just drop the log line or move it to trace.

**Comment by jsumners** [comment]
I vote drop. If moved to trace, then it should write out something like:

`[fastify-compress] no payload to compress, skipping`

**Comment by mcollina** [comment]
let's drop
