### ISSUE TITLE
Why log when there's no payload?

### ISSUE THREAD

**Issue by sergiz** [fastify/fastify-compress#127]
Hello

https://github.com/fastify/fastify-compress/blob/fac731f2375a2952bf0e731d60c11cb187cecfee/index.js#L212

What is the purpose of logging this? This kinda makes using code 204 useless if you do not want to spam your log.

https://github.com/fastify/fastify-compress/issues/114 https://github.com/fastify/fastify-compress/pull/115
It's supposed to be gone already, but it's still here

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
