### ISSUE TITLE
Corrupted reply with async prefixed routes and br encoding

### ISSUE THREAD

**Issue by cameronmbell** [fastify/fastify-compress#140]
## 🐛 Bug Report

The JSON response becomes corrupted when using br compression as well as prefixed async routes, This may be the unresolved cause of https://github.com/fastify/fastify-compress/issues/104

## To Reproduce

```js
// package.json
{
  "name": "node_test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "fastify": "^3.9.2",
    "fastify-compress": "^3.4.0"
  }
}
```
```js
// index.js
const server = require('fastify')();

server.register(require('fastify-compress'), {
    threshold: 0,
    // the issue disappears by excluding 'br' from the encodings
    // encodings: ['gzip', 'deflate', 'identity']
});

server.register(require('./routes'));

server.listen(8080);
```
```js
// routes/index.js
module.exports = async (fastify, _) => {
    fastify.register(require('./test'), {
        prefix: '/test', // if this prefix is removed, the issue disappears
    });
}
```
```js
// routes/test.js
module.exports = async (fastify, opts) => {
    fastify.get('/', opts, async (req, _) => {
        return { hi: true };
    });
}
```
If a GET request is made to `http://localhost:8080/test` the response body is:
```js
�{"hi":true}
```
Note the expected behavior is produced if the prefix in routes/index.js is removed, or if 'br' encoding is explicitly removed when registering fastify-compress

## Expected behavior

```js
{"hi":true}
```

## Your Environment

- *node version*: v14.15.1
- *fastify version*: >=3.9.2
- *os*: Windows 10
- *GET request was made with the chrome fetch API & postman and results were the same*

**Comment by mcollina** [comment]
#141 fixes it
