### ISSUE TITLE
replace deprecated node-zlib

### ISSUE THREAD

**Issue by naseemkullah** [fastify/fastify-compress#143]
Thoughts on replacing node-zlib with nodejs core's zlib ?

> This extension is deprecated since the functionality was folded into node.js core: https://nodejs.org/dist/latest/docs/api/zlib.html

**Comment by mcollina** [comment]
> Thoughts on replacing node-zlib with nodejs core's zlib ?

Where does this comes from? We don't list this in our package.json.

Anyway, feel free to send a PR to address this!

**Comment by naseemkullah** [comment]
> > Thoughts on replacing node-zlib with nodejs core's zlib ?
> 
> Where does this comes from? We don't list this in our package.json.
> 
> Anyway, feel free to send a PR to address this!

I misunderstood the code, it indeed already uses the core's zlib. 🤦 

Sorry for the bother!
