### ISSUE TITLE
Add to docs info that "fastify-compress" MUST be registered BEFORE "fastify-static".

### ISSUE THREAD

**Issue by amokmen** [fastify/fastify-compress#164]
## Feature Proposal

According to [it](https://github.com/fastify/fastify-static/issues/45#issuecomment-616190240), could you add to docs something like this, please:
> You MUST *register* the `fastify-compress` *global hook* BEFORE registering `fastify-static`.

## Motivation

For save people's time. Because I lost a bit time trying to understand why compression is not working for me.

**Comment by kibertoad** [comment]
Would you consider sending PR for this?

**Comment by amokmen** [comment]
Okay, let's go long way :)
