### ISSUE TITLE
Add ability to append 'vary' response header rather than create a new one

### ISSUE THREAD

**Issue by Fdawgs** [fastify/fastify-compress#172]
## 🚀 Feature Proposal
At present, this plugin creates a new 'vary' header, even if one already exists, leading to the vary header becoming an array internally (`vary: ["Origin", "accept-encoding"]`) and presenting as multiple headers in a response: 

```
vary: Origin
vary: accept-encoding
```

It would be good if a plugin could append an existing vary header i.e. `vary: Origin, accept-encoding`, similar to what the [fastify-cors](https://github.com/fastify/fastify-cors) plugin does, preferably with an optional boolean option in the config.

## Motivation

Whilst the above example is perfectly valid, some clients struggle with multiple headers with the same name (legacy medical systems basically).

## Example

```js
fastify.register(
  require('fastify-compress'),
  { appendVaryHeader: true }
)
```

**Comment by mcollina** [comment]
What's the best implementation of the spec?

**Comment by Fdawgs** [comment]
According to [Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2), both of the examples below are perfectly valid:

```
vary: Origin, Accept-Encoding
```

```
vary: Origin
vary: Accept-Encoding
```

Unfortunately, the client systems I'm working with completely ignore that spec. 😠

**Comment by zekth** [comment]
I'll work on it.

**Comment by Fdawgs** [comment]
> I'll work on it.

You're a wizard @zekth, thanks!
