### ISSUE TITLE
Conditionally Enable Content-Length Header

### ISSUE THREAD

**Issue by Verequies** [fastify/fastify-compress#193]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm currently using Fastify and Fastify-Compress for a project. 

Spent quite a while trying to figure out why the downloads from my Fastify server are reporting unknown in size. I noticed that after disabling compression, my Content-Length header is not being stripped from the output.

Doing some research on previous issues it appears there was one issue that was the core reason for it's removal (https://github.com/fastify/fastify-static/issues/52). As I require this feature in my project it would be great if the 'Content-Length' header was not stripped from the request response. If its by default disabled, that is fine, as long as you can turn it on.

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by darkgl0w** [comment]
@Verequies can you please provide a little example exposing your use case so I can make sure that I cover your needs with my PR ?

**Comment by Verequies** [comment]
@darkgl0w, apologies for the late reply. I had a look at the PR and it seems to cover my case. I basically just needed a way to enable the header so that download sizes were reported correctly. Thank you for adding that ability.

**Comment by Verequies** [comment]
Looks like it would work, but the TypeScript types haven't been updated so I get a compilation error.

**Comment by darkgl0w** [comment]
Oups I totally forgot about the types :facepalm: 
I will submit a PR in a few minutes.

**Comment by Verequies** [comment]
@darkgl0w Thanks, how can I easily test this PR? Or do I need to wait for a minor version update with the updated types included?

**Comment by darkgl0w** [comment]
@Verequies it will be published as a patch version I think (so expect a `4.0.1` version).
If you want to test the changes you can
```sh
npm uninstall fastify-compress && npm install --save darkgl0w/fastify-compress#update-types
```

Just don't forget to revert to the official package.

**Comment by darkgl0w** [comment]
@Verequies `fastify-compress@4.0.1` has been released ^^

You can `npm install -s fastify-compress@latest` to use it in your project.

**Comment by Verequies** [comment]
@darkgl0w thanks for the heads up! I have gone and switched this to the latest stable release now.

**Comment by Verequies** [comment]
Recently started a new project and require the `content-length` header, unfortunately it seems since Fastify 4 and everything being updated to that, the `removeContentLengthHeader` option no longer works when set to `false`. I am not entirely sure why, however disabling compression globally makes the header return.

**Comment by climba03003** [comment]
When `compression` happen, it returns the data into `stream`.
So, `Transfer-Encoding: chunked` will be applied and `Content-Length` will be removed to follow the spec.

See https://github.com/fastify/fastify/pull/3814

**Comment by Verequies** [comment]
Interesting, did not know that. Though back when I tested this end of 2021 that did not happen.
Looking at the test code it looks like you have to specifically add the header if you want it to appear.
I am not doing this as I actually want the content length after the file has been compressed.

What would be the best way to tell the client how large the file is before the download has been completed and get download progress?
