### ISSUE TITLE
Empty reply data in Fastify async route 

### ISSUE THREAD

**Issue by vitalikprac** [fastify/fastify-compress#237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

6.1.0

### Node.js version

16.15.0

### Operating system

Windows 11

### Browser

Chrome 102

### Description

The route of fastify has handler function and it's work as expected.   
```js
fastify.get('/', (request, reply) => {
    reply.send('hello world');
})
```
Browser show the correct response headers and render 'hello world' to html
![image](https://user-images.githubusercontent.com/42850697/176319115-0bfe2ccb-5e7b-40bd-9b3e-9c5a205f20d6.png)
![image](https://user-images.githubusercontent.com/42850697/176319184-1b99256a-77f4-4f25-97e1-11c1132b13ff.png)

But if we changed handler function to async, it has strange behaviour
```js
fastify.get('/', async(request, reply) => {
    reply.send('hello world');
})
```
In browser, response headers displays `content-length: 0`
![image](https://user-images.githubusercontent.com/42850697/176319306-e330d81d-45fd-4796-991f-00e008e49a66.png)
And browser says that request has no response data available

If I understand correctly https://github.com/fastify/fastify-compress/issues/140 issue should resolve my problem , but it would not work for me.

### Steps to Reproduce

1. Init project with yarn or npm
2. Add `fastify` and `@fastify/compress`
``` package.json
{
  "name": "test-fastify",
  "version": "1.0.0",
  "main": "node server.js",
  "type": "module",
  "license": "MIT",
  "dependencies": {
    "@fastify/compress": "^6.1.0",
    "fastify": "^4.2.0"
  }
}
```
3.
```bash 
$ yarn install
```
4. Create `server.js` file
```js
import Fastify from 'fastify';
import FastifyCompress from '@fastify/compress';

const fastify = Fastify();
await fastify.register(FastifyCompress, { threshold: 0 });
fastify.get('/', async(request, reply) => {
    reply.send('hello world');
})
await fastify.listen({ port: 3000 })
```
5. 
```bash 
$ yarn start
```
6. Open Browser or Postman at http://localhost:3000
7. View Response directly on the page or in Dev Tools
![image](https://user-images.githubusercontent.com/42850697/176320426-9fadc455-c04d-452d-82b0-c014d6d25170.png)
![image](https://user-images.githubusercontent.com/42850697/176320442-527c15e0-270e-4b29-8c6e-9e3d6afef1ea.png)

### Expected Behavior

Browser should render `hello world` in async fastify handler as it does in non-async handler

**Comment by mcollina** [comment]
Thanks for reporting.

We changed the default behavior in V4, promoting a good promise hygiene.

Your promise returns `undefined`, so that's what you get.

```js
fastify.get('/', async(request, reply) => {
  return 'hello world'
})
```

or

```js
fastify.get('/', async(request, reply) => {
  reply.send('hello world')
  return reply
})
```

**Comment by vitalikprac** [comment]
Thanks, it's work for me. 
Also would be nice if you add example with async function to README for better developers experience.

**Comment by goriunov** [comment]
Just had the same issue, interesting enough non-compressed objects work properly, basically, we had API in production that would just do reply.send() and till we hit the compression limit everything worked fine, after that the whole API went blank...

Wondering if there would be the same behaviour for compressed and non-compressed cases to make sure we can pick up the issue during testing etc.
