### ISSUE TITLE
[feature] Add flush method

### ISSUE THREAD

**Issue by IanVS** [fastify/fastify-compress#240]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add a way to flush a response immediately without compressing.

### Motivation

I'm attempting to migrate storybook's dev server from express to fastify, but I'm by no means very familiar with fastify.  I found that they have been using a `res.flush()` method which comes from express' `compression` middleware (https://www.npmjs.com/package/compression/v/1.2.1).  

Is there already a way to do this in fastify?  I wasn't able to find one.

**Comment by mcollina** [comment]
What's your use case exactly? There are a few options available to define a route that does not compress a payload.

**Comment by IanVS** [comment]
It is a "progress" reporter, that streams a completion percentage to the browser: https://github.com/storybookjs/storybook/blob/c9225ab13b01deddf2a5b9093102e1963f8aca8e/lib/core-common/src/utils/progress-reporting.ts#L31

**Comment by mcollina** [comment]
You can declare that route to skip compression, take a look at the readme.

**Comment by IanVS** [comment]
OK thanks for the quick response!

**Comment by mcollina** [comment]
No worries!
