### ISSUE TITLE
reply.compress is not working as expected

### ISSUE THREAD

**Issue by danielecr** [fastify/fastify-compress#246]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

6.1.1

### Node.js version

18.10.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Alpine Linux 3.16 with node 18

### Description

as documented, I registered the plugin with code:

```
fastify.register(require('@fastify/compress'),{global: false })
```
then tried to use `reply.compress()` I have this error (and crash):
```
/home/node/code/models/stream-result.js:46
      reply.type('application/json').compress(piped);
                                     ^

TypeError: reply.type(...).compress is not a function
```
piped is a stream, and replacing with `compress` with `send` works

### Steps to Reproduce

not sure if it is needed to pass reply object to an external function to reproduce the error

### Expected Behavior

It should accept a stream and stream it.

**Comment by climba03003** [comment]
I recommend you use the form of 

```ts
import fastifyCompress from '@fastify/compress`

fastify.register(fastifyCompress, { global: false })
```

It often the problem of the user do not configure `TypeScript` correctly. So, the `type merging` is not working.

**Comment by climba03003** [comment]
I may mis-understand the issue. It is not TypeScript related.

You are required to use `await` the registration for it works.

```js
await fastify.register(require('@fastify/compress'),{global: false })
```

**Comment by danielecr** [comment]
```
(async () => {
    await fastify.register(require('@fastify/compress'),{threshold: 2048, global: true })
    console.log("compress ok");
})();
```
"compress ok" is printed. But still "reply.compress is not a function"

For curiosity I added console.log() before line 204, in
https://github.com/fastify/fastify-compress/blob/master/index.js#L204

and it is not printed. The reply is used for a http POST method, I do not know if it changes something

**Comment by climba03003** [comment]
https://github.com/fastify/fastify-compress/blob/430b4f35b989753affe1c792bed913560029f20b/test/routes-compress.test.js#L133-L158

**Comment by danielecr** [comment]
> https://github.com/fastify/fastify-compress/blob/430b4f35b989753affe1c792bed913560029f20b/test/routes-compress.test.js#L133-L158

and is it possible to add a `fastify.post(...)`  test case?

**Comment by climba03003** [comment]
> is it possible to add a fastify.post(...) test case?

I didn't see how `.post` is related, but welcome to add one.

**Comment by danielecr** [comment]
> > is it possible to add a fastify.post(...) test case?
> 
> I didn't see how `.post` is related, but welcome to add one.

I don't get the point, why it is not working using commonjs? isn't cjs supported anymore?

**Comment by danielecr** [comment]
> > I don't get the point, why it is not working using commonjs? isn't cjs supported anymore?
> 
> It is supported in `commonjs`. And I have no idea why it didn't works for you without a minimal repo.
> 
> My guess is about there are something wrong about your setup. For example, the routes and `@fastify/compress` are inside separate encapsulation context.
> 
> Another though is all the `plugin` is registered inside the same file. And you did not `await` that file in the most upper layer.

Thank you so much! Exactly that. Now I get it, it was not the "right fastify object" the one I attached the route, and that means the better way to make compress works with commonjs is to wrap all in a async start function
