### ISSUE TITLE
Regarding content encoding priorities in fastify/compress

### ISSUE THREAD

**Issue by Shishira1203** [fastify/fastify-compress#257]
## 💬  Question
Hi. how do I define custom encoding priorities for supported `Content-Encoding` types in fastify/compress?

The [documentation](https://github.com/fastify/fastify-compress#customize-encoding-priority) states that I can define my custom encodings array with the priorities but I could not get it to work. Even though I define encodings array as ["gzip", "deflate", "br"] (prefer gzip over deflate and deflate over br), I am still seeing responses compressed using br for the requests with `Accept-Encoding: gzip, deflate, br`. Any help? Thanks

## Your Environment

- *node version*: 16
- *fastify version*: >=3.0.0
- *os*: Windows

**Comment by climba03003** [comment]
Would you like to send a PR to address the issue?

**Comment by Shishira1203** [comment]
Sure!

**Comment by Shishira1203** [comment]
@climba03003 I don't seem to have commit-access to this repository. Can you please help me with the access?

**Comment by climba03003** [comment]
> Can you please help me with the access?

1. Fork the repository
2. Clone from your fork
3. Create a new branch based on `master`
4. Commit new code
5. Push the code to your fork
6. Submit Pull Request on Github
