### ISSUE TITLE
The response is not getting compressed when sending accept-encoding as gzip?

### ISSUE THREAD

**Issue by kp198** [fastify/fastify-compress#266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

```
import fastify from "fastify";
const server = fastify({ logger: true });
server.register(import("@fastify/compress"), {
      global: true,
      threshold: 1,
    });
server.get("/", (req, reply) => {
  console.log("trust");
  reply.code(200).send("hi");
});
const start = async () => {
  try {
    await server.listen({ host: "0.0.0", port: 8083 });
  } catch (error) {}
};

start();
```

This is a bare bones example of using compress i came up with but the content-encoding is not seen in the browser response headers.
 Can someone tell me where I am going wrong here?
Added logs inside the _onRoute_  , hook (line 52) but it is not getting printed.

Fastify: 4.20.0
compress: 6.4.0

**Comment by gurgunday** [comment]
It happens because you need to `await` the plugin when registering:
```js
await server.register(import("@fastify/compress"))
```
