### ISSUE TITLE
Accept-Encoding should not be added to 'Vary' for non-compressable Content-Types

### ISSUE THREAD

**Issue by rasander** [fastify/fastify-compress#279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

6.5.0

### Node.js version

20.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Mac OS X and Linux Ubuntu

### Description

"Accept-Encoding" is always added to Vary for both compressable and  non-compressable content-types.
This should only be added if content-type is compressable.

This means, that caching is not working properly in nginx or CDN, because some caching applications (in my case Akamai CDN), will only cache if Content-Encoding is matching Accept-Encoding (in case Accept-Encoding is included in Vary).
For non-compressable content-types these will not match.

### Steps to Reproduce

```
$ curl -I "http://localhost:3000/-/media/test.gif" -X GET -H "Accept-Encoding: br"
HTTP/1.1 200 OK
cache-control: public, max-age=604800
content-type: image/gif
vary: accept-encoding
content-length: 2971239
Date: Mon, 05 Feb 2024 14:50:33 GMT
Connection: keep-alive
Keep-Alive: timeout=72

$ curl -I "http://localhost:3000/-/media/test.gif" -X GET 
HTTP/1.1 200 OK
cache-control: public, max-age=604800
content-type: image/gif
vary: accept-encoding
content-length: 2971239
Date: Mon, 05 Feb 2024 14:50:47 GMT
Connection: keep-alive
Keep-Alive: timeout=72
```

### Expected Behavior

```
$ curl -I "http://localhost:3000/-/media/test.gif" -X GET -H "Accept-Encoding: br"
HTTP/1.1 200 OK
cache-control: public, max-age=604800
content-type: image/gif
content-length: 2971239
Date: Mon, 05 Feb 2024 14:50:33 GMT
Connection: keep-alive
Keep-Alive: timeout=72

$ curl -I "http://localhost:3000/-/media/test.gif" -X GET 
HTTP/1.1 200 OK
cache-control: public, max-age=604800
content-type: image/gif
content-length: 2971239
Date: Mon, 05 Feb 2024 14:50:47 GMT
Connection: keep-alive
Keep-Alive: timeout=72
```

**Comment by Fdawgs** [comment]
> "Accept-Encoding" is always added to Vary for both compressable and non-compressable content-types. This should only be added if content-type is compressable.

@rasander Do you have a link to a spec that states this?

**Comment by stanleyxu2005** [comment]
The VARY header is quite complex, so the code change is a remarkable amount of work

@rasander Can I summerize your statement as follows: 
1. Wherever `response.headers['content-encoding']` is defined (unless the value is `identity`, then the header `vary` should contain `accept-encoding`
2. vice versa

I would suggest 
1. add `t.equal(response.headers.vary, 'accept-encoding')` in all related test cases and then do the code change. 
2. refactor similar code block in `function onSend (req, reply, payload, next) {` and `function compress (params) {` as one shared code block.

**Comment by stanleyxu2005** [comment]
> > "Accept-Encoding" is always added to Vary for both compressable and non-compressable content-types. This should only be added if content-type is compressable.
> 
> @rasander Do you have a link to a spec that states this?

https://www.fastly.com/blog/best-practices-using-vary-header
See the section **How to Use Vary to Solve Problems**
