### ISSUE TITLE
Reply with a long string will encounter "Premature close #215"

### ISSUE THREAD

**Issue by stanleyxu2005** [fastify/fastify-compress#286]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

7.0.1

### Node.js version

18.17.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

Similar issue to #215

I'm sending a long string as response, with `fastify-compress` enabled, it will fail with error `Premature close`.

### Steps to Reproduce

```js

  const fastify = new Fastify({})

  fastify.register(fastifyCompress) // #1 disable this line will work

  fastify.get('/subscription', async (req, reply) => {

    const longString = new Array(1024).fill('a').join('') // <--- build a string, whose length is >= 1024 (compress.threshold)

    // return reply.send(longString) // <--- ok, string will be sent

    reply.send(longString) // <--- not ok, if `return ` is forgotten to be added at block end
  })
```

### Expected Behavior

Regardless `return ` is added or not, it should always respond with expected content.

## Question
Do you think, there is something can be improved in @fastify/compress

**Comment by stanleyxu2005** [comment]
I highly suspect that something is not expected inside fastify/compress

```js
    stream = zipStream(params.compressStream, encoding)
    pump(payload, stream, onEnd.bind(reply))
    next(null, stream)
```

I'm happy to provide the object details of `payload` and `stream`, if it is needed.

**Comment by stanleyxu2005** [comment]
I doubt something is wrong in one of these areas

![image](https://github.com/fastify/fastify-compress/assets/5162687/520ab94d-c8c8-4cba-8a51-2284383d91b5)

**Comment by stanleyxu2005** [comment]
Oh. now I know the issue. but it's very easy to make a mistake. 

For an async route definition, I need to add `return` before  `reply.send()...`, otherwise it never ends.

![image](https://github.com/fastify/fastify-compress/assets/5162687/7ee7498e-7153-4cdd-96d5-5d9edac73029)

**Comment by stanleyxu2005** [comment]
But if I dont enable `@fastify/compress`, w/wo the `return` have no difference. Both works. 
Do you think, there is something can be improved in `@fastify/compress`

**Comment by gurgunday** [comment]
If you have an async handler, you should always return the body instead of using `reply.send`:

```js
  const fastify = new Fastify({})

  fastify.register(fastifyCompress) // #1 disable this line will work

  fastify.get('/subscription', async (req, reply) => {

    const longString = new Array(1024).fill('a').join('') // <--- build a string, whose length is >= 1024 (compress.threshold)

    return longString
  })
```

Or:

```js

  const fastify = new Fastify({})

  fastify.register(fastifyCompress) // #1 disable this line will work

  fastify.get('/subscription', (req, reply) => {

    const longString = new Array(1024).fill('a').join('') // <--- build a string, whose length is >= 1024 (compress.threshold)

    reply.send(longString)
  })
```


You can find more information here: https://fastify.dev/docs/latest/Reference/Routes/#promise-resolution

**Comment by stanleyxu2005** [comment]
@gurgunday Thanks for sharing info. 

It's a bit tricky for a new user. I'd now strictly call `return reply.send(...)`. Syntax sugar is painful when migrating between different frameworks. 

I was not aware this when migrating from Koa of promise based routes.
```js
// in koa
async someGetRoute(ctx) {
  ctx.body = await getMyDataAsync()
}

// in fastify
async someGetRoute(request, reply) {
  return reply.send(await getMyDataAsync())
}
```
