### ISSUE TITLE
7.0.1 changes the brotli default quality

### ISSUE THREAD

**Issue by fozcode** [fastify/fastify-compress#287]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, this is not an issue as such, just an observation and you can close it as you wish.

I had a test failure moving from 7.0.0 to 7.0.1 because for my use case of compressing text the brotli response went from being smaller than gzip to being larger. I'm not sure what the default quality was in 7.0.0 but apparently it wasn't `4`.

```
7.0.0: plain text: 74081, gzip: 7736, br: 6716
7.0.1: plain text: 74081, gzip: 7736, br: 8436
```

I'm now explicitly setting the `brotliOptions` to get the better compression but I thought you might like to know that with the 'out of the box' defaults gzip is now giving better compression for some payloads.

**Comment by stanleyxu2005** [comment]
This is on purpose. From v7.0.1, the default brotli compression level is changed to `4` instead of `11`.  
`11` means maximal compression ratio but it is remarkably slow.
`4` is a balanced value. 
Sure you can explicit to set it to a best value for your own project.

**Comment by gurgunday** [comment]
Thank you for the issue!

As explained by @stanleyxu2005, this change was supposed to be made in `v7.0.0` but unfortunately did not work, so the patch release has simply fixed that bug

**Comment by fozcode** [comment]
Thanks for clarifying! My bad for not going further back to see that this was the reason for v7. Appreciate the fast response.
