### ISSUE TITLE
Unicode emoji converted to broken chars in certain extreme long string responses

### ISSUE THREAD

**Issue by stanleyxu2005** [fastify/fastify-compress#288]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

7.0.2

### Node.js version

18.x

### Operating system

Windows

### Description

Download a 200kb yaml plain text file with `fastify/compress`. Certain lines of the yaml contains illegal chars. 

![image](https://github.com/fastify/fastify-compress/assets/5162687/33599abb-72fb-4038-9e19-dabaf1269d2b)

As you can see, on the left side (without compress), icons in the small green box are same. 
But on the right side, one of the icon becomes 2 strange question marks.

The content encoding is `br` (I tried with `gzip`, same error)

![image](https://github.com/fastify/fastify-compress/assets/5162687/673a9422-6d59-45fd-afea-7bdd37a894e1)

Any thoughts, what can be the root cause? 

### Steps to Reproduce

```js
const fastify = new Fastify({})
fastify.register(fastifyCompress)

fastify.get('/subscription', async (req, reply) => {
  const subscription = await handler.downloadClashSubscriptionAsync(config)

  // await require('fs').promises
  //   .writeFile('/out.txt', subscription, 'utf-8')  // <--- the file content is okay

  return reply.send(subscription)  // <--- the file content is corrupt
})
```

### Expected Behavior

Dont expect the two question marks appear in the content.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mcollina** [comment]
As some additional checks: can you verify that Node.js brotli compressor is not the source of the problem?

**Comment by stanleyxu2005** [comment]
> As some additional checks: can you verify that Node.js brotli compressor is not the source of the problem?

How can I verify on Node.js side? I have configured supported encoding, so I have tested with `br`, `gzip`, `deflate`. No difference.

**Comment by mcollina** [comment]
Take a look at the zlib module.

**Comment by stanleyxu2005** [comment]
> Take a look at the zlib module.

Hmm. It can be this case. I'm using some tricky to run Node v18 on unsupported Windows system... Maybe it's related...

Anyway, If I add at least one space at the beginning of the string, the output will be correct
```js
   return reply.send(' ' + subscription) // <--- works
```

**Comment by stanleyxu2005** [comment]
[clash.zip](https://github.com/fastify/fastify-compress/files/14794167/clash.zip)
Attached a minimal reproducible example. 

```bash
npm install
node issue288.js
```

Open browser and navigate to http://127.0.0.1:6789/issue
When you see the whole file, then search for `hydra.alibaba.com`

**Comment by mcollina** [comment]
<img width="636" alt="Screenshot 2024-03-28 at 20 04 37" src="https://github.com/fastify/fastify-compress/assets/52195/0b60187f-c01c-424a-9f12-ca00df0e6a06">


renders perferctly here.

**Comment by mcollina** [comment]
I think you might need to specify the charset in the http header.

```js
const Fastify = require('fastify')
const fastifyCompress = require('@fastify/compress')

const fastify = new Fastify({
  logger: true,
})
fastify.register(fastifyCompress)

fastify.get('/issue', async (req, reply) => {
  const subscription = await require("fs")
    .promises //
    .readFile("./subscription.txt", "utf-8");

  // await require('fs').promises
  //   .writeFile('/out.txt', subscription, 'utf-8')  // <--- the file content is okay
  //

  reply.header('Content-Type', 'text/plain; charset=utf-8')

  return reply.send(subscription)  // <--- the file content is corrupt
})

fastify.listen({ port: 6789, host: '127.0.0.1' })
```

**Comment by stanleyxu2005** [comment]
> I think you might need to specify the charset in the http header.
> 
> ```js
> const Fastify = require('fastify')
> const fastifyCompress = require('@fastify/compress')
> 
> const fastify = new Fastify({
>   logger: true,
> })
> fastify.register(fastifyCompress)
> 
> fastify.get('/issue', async (req, reply) => {
>   const subscription = await require("fs")
>     .promises //
>     .readFile("./subscription.txt", "utf-8");
> 
>   // await require('fs').promises
>   //   .writeFile('/out.txt', subscription, 'utf-8')  // <--- the file content is okay
>   //
> 
>   reply.header('Content-Type', 'text/plain; charset=utf-8')
> 
>   return reply.send(subscription)  // <--- the file content is corrupt
> })
> 
> fastify.listen({ port: 6789, host: '127.0.0.1' })
> ```

In my initial report, the response header already contains `'Content-Type', 'text/plain; charset=utf-8'`. No need to add this. 
The test result you see is not at the correct place. The broken icon only appears after `hydra.alibaba.com`. 
(However, the mock text file I shared already contains the broken char, so the text is useless)

**Comment by mcollina** [comment]
<img width="376" alt="Screenshot 2024-03-28 at 20 19 42" src="https://github.com/fastify/fastify-compress/assets/52195/0cf467dc-29fd-47e1-a6dc-0fc1d68b25bd">


I can see the same broken icons in nVIM

**Comment by stanleyxu2005** [comment]
> <img alt="Screenshot 2024-03-28 at 20 19 42" width="376" src="https://private-user-images.githubusercontent.com/52195/317854019-0cf467dc-29fd-47e1-a6dc-0fc1d68b25bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTM5MTYsIm5iZiI6MTcxMTY1MzYxNiwicGF0aCI6Ii81MjE5NS8zMTc4NTQwMTktMGNmNDY3ZGMtMjlmZC00N2UxLWE2ZGMtMGZjMWQ2OGIyNWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE5MjAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOWQ0YmI3Mjc2YzcwMjQ2YmVkYmQyYjQ4YzgyYmY2YTYzMWQ4MTc0ZDBkNDU1OTI3NWE4NTBlMDZkMTRmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20LcPfWBjrthPxebktu0iuXmTY-6U6ff86l8HeWCX7s">
> I can see the same broken icons in nVIM

Yes. But how can I explain.. 

My route is like proxy. It downloads a file from external and then sent to my local env.

The actual corrupt raw file is received from external . But I cannot just share , because it contains my private credential. 

But if I make any changes to this received corrupt content, the broken question marks will be gone.

This time you are able to see the broken question marks, because it is already in `subscription.txt`. Sorry.

**Comment by jsumners** [comment]
It is impossible for anyone to assist if you are unable to provide a known good input file that results in a bad output file after being compressed.

```js
const data = fs.readFileSync('/tmp/known_good.txt')
const compressedData = zlib.brotliCompressSync(data)
fs.writeFileSync('/tmp/compressed.txt.brotli', compressedData)
```

```sh
$ brotli -d /tmp/compressed.txt.brotli
```

**Comment by stanleyxu2005** [comment]
> It is impossible for anyone to assist if you are unable to provide a known good input file that results in a bad output file after being compressed.
> 
> ```js
> const data = fs.readFileSync('/tmp/known_good.txt')
> const compressedData = zlib.brotliCompressSync(data)
> fs.writeFileSync('/tmp/compressed.txt.brotli', compressedData)
> ```
> 
> ```shell
> $ brotli -d /tmp/compressed.txt.brotli
> ```

![image](https://github.com/fastify/fastify-compress/assets/5162687/055eecea-aa99-4176-9540-fb63709caf5b)

@jsumners I have done the steps, brotli is fine, but final result is not good. 

Let me describe:

**Round 1:**
1. Download the file "known_good.txt" from external
2. Open "known_good.txt" in editor (e.g. Sublime, Intellij), content is good.
3. Use `return reply.send(known_good_data)` will see broken chars.

**Round 2:**
1. Use @jsumners code snippet to generate `compressed.txt.br` and then decompress it.
2. Use `diff known_good.txt compressed.txt` will show 0 diff.
3. Use `return reply.send(compress_txt_data)` will still see broken chars.

Some conclusions:
1. Brotli compress does not corrupt the data
2. I'm suspect the handling of `reply.send(...)` e.g. hook needs further analysis
3. Not sure if invisible bytes at the beginning of the text data has some impact.

**Comment by Uzlopak** [comment]
Somehow seeing 62484 seems oddly familiar?! As if i saw it in a different context. 

The char is at Position 62484 but it could be byte position 65525, as you mentioned. So very close to the default high watermark of streams?

It can be, that the Buffers are not concatted properly. So basically the following classical misimplementation: toString() is called on each chunk in the stream instead of buffering the chunks into an array of Buffers, run Buffer.concat and then call .toString() once on the result.

**Comment by stanleyxu2005** [comment]
Finally I am able to provide a MRE 
https://github.com/fastify/fastify-compress/files/14794241/issue-288.zip

with masked data to reproduce the issue
[known_good_masked.zip](https://github.com/fastify/fastify-compress/files/14800250/known_good_masked.zip)

**Comment by Uzlopak** [comment]
Can you provide your mvce as a github repo, please.

**Comment by stanleyxu2005** [comment]
> Can you provide your mvce as a github repo, please?

https://github.com/stanleyxu2005/fastify-compress-issue-288
here you go

**Comment by stanleyxu2005** [comment]
Here we go
https://github.com/stanleyxu2005/fastify-compress-issue-288

Now I now the issue. 
I register routes with a route factory, 
https://github.com/stanleyxu2005/fastify-compress-issue-288/blob/main/index.js#L10

If I simply define route as
```js
fastify.get(path, async (request, reply) => {}) // its fine
``` 

If I define route like this, it fails
```js
fastify.register((instance, opts, done) => {
  instance.get(path, async (request, reply) => {}) // its fine
  done
})
```

**Comment by climba03003** [comment]
I am sorry to bother you, but the example you shown above do not reproduce on my computer.
I checked with `fastify.inject` and `Firefox`. All comes out expected result.

**Comment by stanleyxu2005** [comment]
> I am sorry to bother you, but the example you shown above do not reproduce on my computer. I checked with `fastify.inject` and `Firefox`. All comes out expected result.

Could you try toggle the line separator and encoding?
![image](https://github.com/fastify/fastify-compress/assets/5162687/674f4dc6-f41e-4ae9-926a-114b8c1eb2d0)

Sometimes when you checkout a project, Git would do some line separate convertion for you. 
Or you can try to download zipped text.zip and overwrite with the one in project folder.
https://github.com/stanleyxu2005/fastify-compress-issue-288/blob/main/test.zip

**Comment by stanleyxu2005** [comment]
> ![image](https://private-user-images.githubusercontent.com/23028015/318004178-5f6cb2cd-6686-4cea-886a-58a01b6db325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDMwMjQsIm5iZiI6MTcxMTcwMjcyNCwicGF0aCI6Ii8yMzAyODAxNS8zMTgwMDQxNzgtNWY2Y2IyY2QtNjY4Ni00Y2VhLTg4NmEtNThhMDFiNmRiMzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA4NTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliODg0OWYwNmMyZjJiZTBkYzM3MmJkYmJiNWRlZTA3ZTg3YjNmMTg3ODhjNTJjNTJhOWE3Mzk3YWQ0M2RkZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S3Ewpc-vNqSIDbUp4i_9rDrKso1x-KE0FWmsmWd_UrE) So, it is expected to use `LF`? I use Windows and clone it. Git will auto use CRLF.

@climba03003 @Uzlopak Could you pull my repo again. 
I have added a `index2.js`. This time, the string will be generated on-the-fly.

`npm run serve2`

* Navigate to http://127.0.0.1:6789/issue and search for � , You will find 4
* Navigate to http://127.0.0.1:6789/good and search for � , You will find 0
![image](https://github.com/fastify/fastify-compress/assets/5162687/5791d432-b251-4dd4-81aa-9db80e89686f)

![image](https://github.com/fastify/fastify-compress/assets/5162687/4929acee-d9b2-44bd-962e-ef4f4335cd13)

**Comment by mcollina** [comment]
I can reproduce. Note that `/good` has _no compression_ enabled in the example, so that's why it works. The bug is in the `intoStream` module.

**Comment by climba03003** [comment]
I suspect the bug is actually cause by `into-stream`, when using `Readable.from` directly. It works as expected.

**Comment by climba03003** [comment]
For workaround,

1. Bypass `into-stream` using `Readable.from` directly and specify the `Content-Type` header.

```js
instance.get('/issue', async (req, reply) => {
  const longStringWithEmoji = await readFile("./test.txt", "utf-8");
  reply.header('content-type', 'text/plain; charset=utf-8')
  return reply.send(Readable.from(longStringWithEmoji, { encoding: 'utf-8'}))
})
```

2. Use `createReadStream` directly

```js
instance.get('/issue', async (req, reply) => {
  reply.header('content-type', 'text/plain; charset=utf-8')
  return reply.send(createReadStream('./test.txt', 'utf-8'))
})
```

**Comment by mcollina** [comment]
Here is the fix: https://github.com/fastify/fastify-compress/pull/289

**Comment by stanleyxu2005** [comment]
Please reopen the issue, until #291 is tested successfully. Thanks
