### ISSUE TITLE
Content-Length is not included in repsonse header, even when removeContentLengthHeader is false

### ISSUE THREAD

**Issue by stanleyxu2005** [fastify/fastify-compress#296]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

7.0.3

### Node.js version

18.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11

### Description

I'm not sure if it is introduced recently. When I download compressed json resource, the response header does not contain "Content-Length" (case insensitive). 

If the raw json content length > 1024 (compressed), the header is missing.
If the raw json content length < 1024 (uncompressed), the header is there.

May I know, if the content length is normally automatically calculated or it must be specified by application itself? 

```js
fastify.register(fastifyCompress, { global: true, removeContentLengthHeader: false })
```

### Steps to Reproduce

Hope the description is clear enough for your attention :D

**Comment by stanleyxu2005** [comment]
Maybe it is self explained 
https://github.com/fastify/fastify-compress/issues/193#issuecomment-1535630834

**Comment by mcollina** [comment]
This is what it does: https://github.com/fastify/fastify-compress/blob/2848372bb5ce496b0049f278203f942add2ce3f8/index.js#L284-L285.

There is content-length for compressed resources because we cannot know beforehand.

**Comment by stanleyxu2005** [comment]
> This is what it does:
> 
> https://github.com/fastify/fastify-compress/blob/2848372bb5ce496b0049f278203f942add2ce3f8/index.js#L284-L285
> 
> .
> There is content-length for compressed resources because we cannot know beforehand.

okay. thanks
