### ISSUE TITLE
About warning compress: missing payload'

### ISSUE THREAD

**Issue by Wykks** [fastify/fastify-compress#37]
In global mode, I'm getting "compress: missing payload" when I use `reply.redirect`.

Logging this warning directly in the `onSend` global hook when there's no payload seems a bit too much
https://github.com/fastify/fastify-compress/blob/c6afb98d04980254e700d23eaa5561e29f377593/index.js#L79-L82

**Comment by delvedor** [comment]
Good point! @mcollina any ideas on how fix this?

**Comment by mcollina** [comment]
I think we should remove that warning really, or maybe make it a debug.
Would you like to send a PR?
