### ISSUE TITLE
Native Brotli implementation

### ISSUE THREAD

**Issue by manniL** [fastify/fastify-compress#45]
Hey :wave: 

As Brotli is natively available in Node 11, could we use that (if the used Node version supports it) by default? :thinking:

**Comment by mcollina** [comment]
Sure, would you like to send a PR?

Il giorno mar 19 feb 2019 alle 20:20 Alexander Lichter <
notifications@github.com> ha scritto:

**Comment by manniL** [comment]
Not before Thursday, but I'm up to that, yes! :relaxed:
