### ISSUE TITLE
Compression not working for static Assets

### ISSUE THREAD

**Issue by musdy** [fastify/fastify-compress#46]
Compression not working for Static assets.

<img width="926" alt="screenshot 2019-02-22 at 13 32 55" src="https://user-images.githubusercontent.com/1327946/53246146-c1c71980-36a7-11e9-9c9a-dea453130505.png">

Is there a way to enable Fastify Compress to work with Fastify-Static?

Current code:

`fastify.register(require("fastify-compress"));

fastify.register(require("fastify-static"), {
  root: path.join(__dirname, "assets"),
  prefix: "/assets" // optional: default '/'
});`

Thank you.

**Comment by cemremengu** [comment]
Can you try setting the `threshold` option to `0` for compress plugin?

**Comment by mcollina** [comment]
I think you are not serving those files via fastify-static. I _think_ those files are served directly from `nextjs` .

**Comment by musdy** [comment]
Hello @mcollina . I've tried using:

fastify.use(require("compression")());

But have been receiving "this._implicitHeader is not a function" error. Using Next JS with Fastify with compression.

Node version: v11.10.0
Npm version: 6.7.0

**Comment by musdy** [comment]
Tried using fastify/fastify-compress as well. Then I receive:

TypeError [ERR_HTTP2_INVALID_CONNECTION_HEADERS]: HTTP/1 Connection specific headers are forbidden: "connection"

**Comment by mcollina** [comment]
@musdy that will be fixed in the next 1.x release (next week).

**Comment by jibin2706** [comment]
fastify compress was not working when using nextjs

I tried  `fastify.register(require("fastify-compress"))`

**Comment by mcollina** [comment]
nextjs bypass fastify completely and render straight to the http response
object. It cannot work with nextjs.

Il giorno mar 13 ago 2019 alle 13:25 Jibin Thomas <notifications@github.com>
ha scritto:
