### ISSUE TITLE
Conflict with aws-serverless-express

### ISSUE THREAD

**Issue by dalisoft** [fastify/fastify-compress#60]
When using this module, my Lambda app stopping work and somehow causes error and content isn't shown.

I firstly [think](https://github.com/fastify/fastify/issues/1659) issue relates to fastify, but isn't, bug related to this plugin

**Comment by Eomm** [comment]
Do you have any stack trace?
Which version of node is running in the lambda? (node 12 is not supported for what I know)

**Comment by dalisoft** [comment]
Error causing sometime, but it encodes content which can't shown by `aws-serverless-express`.
Content becomes like this `\ux12393<?>` when using this plug-in, it is ok for old ways, but when using lambda mode, this not works

**Comment by mcollina** [comment]
Having a self-contained repro that we can use to track down this bug would help.

**Comment by dalisoft** [comment]
Let's just close this bug as this case very rarely, repo lives [here](https://github.com/dalisoft/fastify-dev-env)
