### ISSUE TITLE
Brotli is never chosen

### ISSUE THREAD

**Issue by TJKoury** [fastify/fastify-compress#61]
Current implementation looks for Accepted-Encoding headers, which are sent in arbitrary order by most browsers, and[ returns the first match](https://github.com/fastify/fastify-compress/blob/master/index.js#L168).  

Plugin needs to have a preferred order option.

**Comment by kumarabhishek** [comment]
@TJKoury , @mcollina  Reason for `brotli` never being chosen is `encoding-negotiator` always returning 'gzip'.  I'm using following workaround:
```
function getEncodingHeader (supportedEncodings, request) {
  const encodingNegotiator = new Negotiator(request);
  // Trying first with brotli
  if(supportedEncodings.includes('br')) {
      return 'br';
  } else {
    return encodingNegotiator.encoding(supportedEncodings)    
  }
}
```

**Comment by Eomm** [comment]
> Current implementation looks for Accepted-Encoding headers, which are sent in arbitrary order by most browsers, and[ returns the first match](https://github.com/fastify/fastify-compress/blob/master/index.js#L168).
> 
> Plugin needs to have a preferred order option.

Could you elaborate?
Do you have a header example and your plugin setup? Do you set the `{ brotli: require('iltorb') }` parameter?

**Comment by kumarabhishek** [comment]
@Eomm  I am using Node.js 12.9.1, so setting `{ brotli: require('iltorb') }` is not needed. I guess for default header in case of chrome `Accept-Encoding: gzip, deflate, br`, it should return 'br'. Atleast i want to prefer 'br' first and then gzip as fallback.

**Comment by Eomm** [comment]
Clear, right now to archive this you could:
- add a `preHandler` that change the header removing all the encoding if `br` is in
- update the client to add the quality score in the header

There is an open PR for this feature but it is stale, would you like to work on it?

**Comment by mcollina** [comment]
I would say a PR on this would be highly welcomed.
