### ISSUE TITLE
Bug: Quality value syntax not supported

### ISSUE THREAD

**Issue by timkendall** [fastify/fastify-compress#70]
It seems like fastify-compress does not support [Quality Value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding#Syntax) syntax in the `Accepts-Encoding` header. This values for example causes a `406 Unsupported Encoding` HTTP error to be returned. 

Looking int the source of [`index.js:128`](https://github.com/fastify/fastify-compress/blob/master/index.js#L126) in `onSend` the `encoding` variable is indeed `null`. This error goes away once removing the `q` directives from the header value.

Example `Accepts-Encoding` header value that we fail to parse:
`gzip;q=1.0,deflate;q=0.6,identity;q=0.3`

Quickly looking at the source, we will likely need to update`getEncodingHeader` to support this.

**Comment by Eomm** [comment]
So the `getEncodingHeader` should return the (supported) encoding with the highest quality value.

Would you like to give it a shot? 💪

**Comment by SerayaEryn** [comment]
I can open a PR that adds support for the quality value syntax.

**Comment by mcollina** [comment]
That would be awesome, thanks!

**Comment by SerayaEryn** [comment]
Just one question:
I wonder if it would be ok to drop the support of node 6.x since it reached end-of-life on April 30?

**Comment by mcollina** [comment]
We’ll drop that on the next major release of Fastify

Il giorno sab 3 ago 2019 alle 13:14 Denis Fäcke <notifications@github.com>
ha scritto:
