### ISSUE TITLE
Not compliant with RFC 7231

### ISSUE THREAD

**Issue by j-windsor** [fastify/fastify-compress#85]
## 🐛 Bug Report

https://tools.ietf.org/html/rfc7231#section-5.3.4

- "If an Accept-Encoding header field is present in a request
   and none of the available representations for the response have a
   content-coding that is listed as acceptable, the origin server SHOULD
   send a response without any content-coding."
- "All content-coding values are case-insensitive"

## To Reproduce

- A request with the header `Accept-Encoding: GzIP` responds HTTP406.
- A request with the header `Accept-Encoding: Invalid` responds HTTP406.

## Expected behavior

- A request with the header `Accept-Encoding: GzIP` should respond with gzip compressed payload.
- A request with the header `Accept-Encoding: Invalid` should respond with uncompressed payload.

## Your Environment

- *node version*: v12.13.0
- *fastify version*: 2.10.0
- *os*: Mac

**Comment by mcollina** [comment]
Good spot! Would you mind sending a PR with a fix?

Il giorno ven 25 ott 2019 alle 06:18 Jay Windsor <notifications@github.com>
ha scritto:
