### ISSUE TITLE
How to compress the output of an ejs template rendered reply without set the global flag

### ISSUE THREAD

**Issue by red1** [fastify/fastify-compress#89]
Hello 
i'm doing something like that : 
`reply.view('/src/templates/hello.ejs', { hello: 'world' })
`
I'd like to compress the output of my ejs template, .compress will not work directly and I don't want to activate the global flag
Do you know how can I do that ? can we enrich the component with a compressOnSend method to accept to be chained and activate the onsend hook ?
`reply.view('/src/templates/hello.ejs', { hello: 'world' }).compressOnSend()`
Thanks

**Comment by mcollina** [comment]
I think this is better solved in the fastify-compress module, adding support for compressing a single route. This is already possible given the internals of the framework, we are only missing support in fastify-compress.

**Comment by red1** [comment]
It would be great yes please!

**Comment by red1** [comment]
Hello @mcollina 
Do you know if this support will be added ?

**Comment by mcollina** [comment]
If somebody would like to work on it, yes!

**Comment by Eomm** [comment]
You could try to implement it 💪

this plugin: https://github.com/fastify/fastify-rate-limit has this kind of feature: global and/or per-route usage, you may get some inspiration from it!

**Comment by marc-fisher-q2e** [comment]
Is there a way to hook into onSend per route? The last per route option in the lifecycle right now is preSerialization so any thoughts on how this could work?

**Comment by Eomm** [comment]
> Is there a way to hook into onSend per route?

No, right now there is not this option, but it should easy to add here:
https://github.com/fastify/fastify/blob/master/lib/route.js#L9

> so any thoughts on how this could work?

Good point, we should add to fastify that parameter, then this issue can be implemented

**Comment by Svjard** [comment]
https://github.com/fastify/fastify-compress/pull/92
