### ISSUE TITLE
Fastify post requests

### ISSUE THREAD

**Issue by hengnee** [fastify/fastify-compress#94]
### PostGraphile with Fastify

I have been using PostGraphile with Fastify and am loving it.
However, there seems to be an issue with compression with POST requests sent using Postman or on the browser.

```javascript
// short snippet of my code.
const fp = require("fastify-plugin");
const AutoLoad = require("fastify-autoload");
const connectToPostgreSQL = require("./db_connection/connectToPostgreSQL");
const registerEnv = require("./utils/register_env");
const compression = require("fastify-compress");
const helmet = require("fastify-helmet");

fastify
    .register(fp(registerEnv))
    .register(fp(connectToPostgreSQL))
    .register(compression, { global: true, threshold: 0 })
    .register(helmet)
    .ready(err => {
      if (err) return console.error(err);
      fastify.log.info("-----------------------------------------------------");
    });
```

May I know if there are anything that I have had done wrongly?

**Comment by mcollina** [comment]
Would you mind to provide a full example to reproduce your problem? Ideally if you could repro with curl as well it would be awesome.

**Comment by hengnee** [comment]
> Would you mind to provide a full example to reproduce your problem? Ideally if you could repro with curl as well it would be awesome.

Yes of course!
And thank you for your prompt reply een though I was slow on my own end..

https://github.com/hengnee/rectify_fastify_postgraphile

**Comment by mcollina** [comment]
This module only works for routes, not for middlewares like postgraphile. Unfortunately there is no real solution for this atm.

You'll need to develop something like https://github.com/mshick/hapi-postgraphile on top of https://github.com/mcollina/fastify-gql

**Comment by hengnee** [comment]
> This module only works for routes, not for middlewares like postgraphile. Unfortunately there is no real solution for this atm.
> 
> You'll need to develop something like https://github.com/mshick/hapi-postgraphile on top of https://github.com/mcollina/fastify-gql

Oh I see. Thank you for rectifying this.
I shall use compression library for now and try to mimic the code from https://github.com/mshick/hapi-postgraphile as much as I possibly can :)

Thank you once again!
