### ISSUE TITLE
official example problem

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify-compress#95]
Hello, i don't  understand example:

```
        threshold: 128
        brotli: brotli
```
is 

```
        threshold: 128,
        brotli: "brotli"
```

okey, need install iltorb
https://www.npmjs.com/package/iltorb

**Comment by StarpTech** [comment]
Check the docs https://github.com/fastify/fastify-compress#brotli

> For Node.js versions that don’t natively support Brotli, it's not enabled by default. If you need it, we recommend installing iltorb and passing it to the brotli option:

**Comment by borodadada** [comment]
thanks
