### ISSUE TITLE
brotli compress

### ISSUE THREAD

**Issue by borodadada** [fastify/fastify-compress#97]
Hello, then i use compress brotli content encoding in browser gz

**Comment by mcollina** [comment]
It would work automatically on recent Node.js, see https://github.com/fastify/fastify-compress/blob/c99f2fab776f0b9139e33f2fdc374be57ef5c29c/index.js#L86.

Is this not working for you?

**Comment by borodadada** [comment]
okey working
fastify.register( require('fastify-compress'), { threshold: 1024, encodings: ['br'] } )
but server latence х10 from gzip ( super slow )

**Comment by mcollina** [comment]
This module does not offer caching for compressed files, and it will compress the file each time it is read. Given that brotli provides better compression, I would expect that it takes longer to compress.

I would recommend to use nginx in front of your Node.js process, as it's an overall better solution for serving files.

**Comment by borodadada** [comment]
mcollina thanks i installed nginx, use http2 + gzip. But i have question, fastify local server - need use http2  or better use http1.1 with out ssl ?
